# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Trata como warning em vez de info (não quebra CI com --fatal-warnings)
    use_build_context_synchronously: warning
    deprecated_member_use: ignore
    library_private_types_in_public_api: ignore
    depend_on_referenced_packages: ignore

linter:
  rules:
    # Desativa regras específicas
    use_build_context_synchronously: false
